apiVersion: v1
# El servicio es una abstracción con nombre de un servicio de software (por ejemplo, mysql)
# que consta de un puerto local (por ejemplo, 3306) en el que escucha el proxy y el selector
# que determina qué pods responderán a las solicitudes enviadas a través del proxy.
kind: Service
metadata:
  # Una cadena que identifica de forma única este objeto dentro del espacio de nombres actuaL. 
  # Este valor se utiliza en la ruta al recuperar un objeto individual.
  name: apache
  # Mapa de claves y valores de cadena que se pueden utilizar para organizar y categorizar
  # (alcance y selección) objetos. Puede coincidir con selectores de controladores de replicación
  # y servicios.
  labels:
    run: apache
# La especificación define el comportamiento de un servicio.
spec:
  # La lista de puertos expuestos por este servicio.
  ports: 
  - port: 80
  # Enrute el tráfico del servicio a pods con claves de etiqueta y valores que coincidan con este selector.
  # Si está vacío o no está presente, se supone que el servicio tiene un proceso externo que administra
  # sus puntos finales, que Kubernetes no modificará. Solo se aplica a los tipos ClusterIP, NodePort
  # y LoadBalancer. Se ignora si el tipo es ExternalName.
  selector:
    run: apache