apiVersion: v1
# PersistentVolume (PV) es un recurso de almacenamiento proporcionado
# por un administrador. Es análogo a un nodo.
kind: PersistentVolume
# Metadatos del objeto estándar
metadata:
  # Una cadena que identifica de forma única este objeto dentro del espacio de nombres actuaL. 
  # Este valor se utiliza en la ruta al recuperar un objeto individual.
  name: pv-volume
  # Mapa de claves y valores de cadena que se pueden utilizar para organizar y categorizar
  # (alcance y selección) objetos. Puede coincidir con selectores de controladores de replicación
  # y servicios.
  labels:
    type: local
# Define una especificación de un volumen persistente propiedad del clúster. 
# Proporcionado por un administrador
spec:
  # Es el nombre de StorageClass a la que pertenece este volumen persistente.
  # El valor vacío significa que este volumen no pertenece a ninguna StorageClass.
  storageClassName: sistemaficheros
  # Descripción de los recursos y la capacidad del volumen persistente.
  capacity:
    # Tamaño del volumen persistente
    storage: 10Gi
  # Contiene todas las formas en que se puede montar el volumen.
  accessModes:
    - ReadWriteOnce
  # Representa un directorio en el host. Provisto por un desarrollador o evaluador.
  # ¡Esto es útil únicamente para desarrollo y pruebas de un solo nodo! El almacenamiento
  # en el host no es compatible de ninguna manera y NO FUNCIONARÁ en un clúster de múltiples nodos
  hostPath:
    path: "/mnt/data"
