apiVersion: v1
kind: Pod
metadata:
  name: pod1
# Especificación del comportamiento deseado del pod
spec:
  # Lista de contenedores pertenecientes al pod. Actualmente no se pueden agregar ni eliminar contenedores. 
  # Debe haber al menos un contenedor en un Pod. No se puede actualizar.
  containers:
    # Nombre del contenedor especificado como DNS_LABEL. Cada contenedor de un pod 
    # debe tener un nombre único (DNS_LABEL). No se puede actualizar.
    - name: test-container
      # Nombre de la imagen del contenedor.
      image: ubuntu
      # Matriz de puntos de entrada. No ejecutado dentro de un shell.
      command: [ "/bin/sh", "-c", "sleep 1000000" ]
      # Lista de fuentes para completar las variables de entorno en el contenedor.
      # Las claves definidas dentro de una fuente deben ser un C_IDENTIFIER. Todas las claves no válidas
      # se informarán como un evento cuando se inicie el contenedor. Cuando una clave existe en varias fuentes,
      # el valor asociado con la última fuente tendrá prioridad. Los valores definidos por un Env con una clave
      # duplicada tendrán prioridad. No se puede actualizar.
      envFrom:
          # SecretEnvSource selecciona un secreto para completar las variables de entorno.
        - secretRef:
          # Nombre del referente.
            name: secreto1
          # SecretEnvSource selecciona un secreto para completar las variables de entorno.
        - secretRef:
          # Nombre del referente.
            kubecname: secreto2
      # Recursos requeridos por este contenedor. No se puede actualizar.
      resources:
        # Los límites describen la cantidad máxima de recursos informáticos permitidos.
        limits:
          memory: "128Mi"
          cpu: "500m"
  restartPolicy: Never
