apiVersion: v1
# Secret contiene datos secretos de cierto tipo. El total de bytes de los valores en el campo Datos
# debe ser menor que los bytes de MaxSecretSize.
kind: Secret
# ObjectMeta son metadatos que todos los recursos persistentes deben tener, que 
# incluyen todos los objetos que los usuarios deben crear.
metadata:
  # El nombre debe ser único dentro de un espacio de nombres. Es necesario al crear recursos,
  # aunque algunos recursos pueden permitir que un cliente solicite la generación de un nombre
  # apropiado automáticamente. El nombre está destinado principalmente a la creación de idempotencia
  # y definición de configuración. No se puede actualizar.
  name: secreto2
# Se utiliza para facilitar el manejo programático de datos secretos.
# Opaco es el tipo de secreto predeterminado si no especifica explícitamente un tipo en un manifiesto secreto.
# Cuando crea un secreto usando kubectl, debe usar el subcomando genérico para indicar un tipo de secreto Opaque.
type: Opaque
# Permite especificar datos secretos no binarios en forma de cadena. Se proporciona como un campo de entrada de
# solo escritura por conveniencia. Todas las claves y valores se fusionan en el campo de datos al escribir,
# sobrescribiendo cualquier valor existente. El campo stringData nunca se muestra al leer desde la API.
stringData:
  usuario2: 'usu2'
  usu2-pass: 'password-usu2'
