apiVersion: v1
# Secret contiene datos secretos de cierto tipo. El total de bytes de los valores en el campo Datos
# debe ser menor que los bytes de MaxSecretSize.
kind: Secret
# ObjectMeta son metadatos que todos los recursos persistentes deben tener, que 
# incluyen todos los objetos que los usuarios deben crear.
metadata:
  # El nombre debe ser único dentro de un espacio de nombres. Es necesario al crear recursos,
  # aunque algunos recursos pueden permitir que un cliente solicite la generación de un nombre
  # apropiado automáticamente. El nombre está destinado principalmente a la creación de idempotencia
  # y definición de configuración. No se puede actualizar.
  name: secreto1
# Se utiliza para facilitar el manejo programático de datos secretos.
# Opaco es el tipo de secreto predeterminado si no especifica explícitamente un tipo en un manifiesto secreto.
# Cuando crea un secreto usando kubectl, debe usar el subcomando genérico para indicar un tipo de secreto Opaque.
type: Opaque
# Los datos contienen los datos secretos. Cada clave debe constar de caracteres alfanuméricos,
# '-', '_' o '.'. La forma serializada de los datos secretos es una cadena codificada en base64,
# que representa aquí el valor de datos arbitrario (posiblemente no una cadena).
data:
  usuario1: dXN1MQ==
  usu1-pass: cGFzc3dvcmQtdXN1MQ==
