apiVersion: v1
# La configuración contiene la información necesaria para construir la conexión a 
# clústeres remotos de Kubernetes como un usuario determinado.
kind: Config
# Contiene información sobre cómo comunicarse con un clúster de Kubernetes. 
clusters:
  # Nombre del cluster
  - name: clusterDESA
    # Configuración del cluster
    cluster:
      # Ruta al archivo del certificado de autoridad del clúster.
      certificate-authority: /home/oem/.minikube/ca.crt

      extensions:
        - extension:
            # Fecha y hora de la última actualización de la extensión.
            last-update: Wed, 16 Aug 2023 23:45:45 -05
            # Proveedor que ofrece la extensión (en este caso, "minikube.sigs.k8s.io").
            provider: minikube.sigs.k8s.io
            # Versión de la extensión.
            version: v1.31.2
          name: cluster_info
      server: https://192.168.49.2:8443
  - cluster:
      certificate-authority: /home/oem/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Thu, 25 Jan 2024 21:34:23 -05
            provider: minikube.sigs.k8s.io
            version: v1.31.2
          name: cluster_info
      server: https://192.168.58.2:8443
    name: minikube
contexts:
  - context:
      cluster: clusterDESA
      extensions:
        - extension:
            last-update: Wed, 16 Aug 2023 23:45:45 -05
            provider: minikube.sigs.k8s.io
            version: v1.31.2
          name: context_info
      namespace: default
      user: clusterDESA
    name: clusterDESA
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Thu, 25 Jan 2024 21:34:23 -05
            provider: minikube.sigs.k8s.io
            version: v1.31.2
          name: context_info
      namespace: default
      user: minikube
    name: minikube
# Nombre del contexto que le gustaría usar de forma predeterminada
current-context: minikube
preferences: {}
users:
  - name: clusterDESA
    user:
      client-certificate: /home/oem/.minikube/profiles/clusterDESA/client.crt
      client-key: /home/oem/.minikube/profiles/clusterDESA/client.key
  - name: minikube
    user:
      client-certificate: /home/oem/.minikube/profiles/minikube/client.crt
      client-key: /home/oem/.minikube/profiles/minikube/client.key
