apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    zone: prod
    version: v1
spec:
  containers:
   - name: nginx
     image: apasoft/nginx:v1
     resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  #NodeSelector es un selector que debe ser verdadero para que el pod se ajuste a un nodo. 
  #Debe coincidir con las etiquetas de un nodo para que el pod sea programado en ese nodo.
  nodeSelector:
    entorno: desarrollo  