apiVersion: v1
kind: Pod
metadata:
  name: pod1
# Especificación del comportamiento deseado del pod
spec:
  # Lista de contenedores pertenecientes al pod. Actualmente no se pueden agregar ni eliminar contenedores. 
  # Debe haber al menos un contenedor en un Pod. No se puede actualizar.
  containers:
    # Nombre del contenedor especificado como DNS_LABEL. Cada contenedor de un pod 
    # debe tener un nombre único (DNS_LABEL). No se puede actualizar.
    - name: contenedor1
      # Nombre de la imagen del contenedor.
      image: ubuntu
      # Matriz de puntos de entrada. No ejecutado dentro de un shell.
      command: [ "/bin/sh", "-c", "sleep 1000000" ]
      # Volúmenes de pod para montar en el sistema de archivos del contenedor.
      # No se puede actualizar. VolumeMount describe un montaje de un volumen dentro de un contenedor.
      volumeMounts:
        # Debe coincidir con el nombre de un volumen.
      - name: volumen-secretos
        # Ruta dentro del contenedor en la que se debe montar el volumen. No debe contener ':'.
        mountPath: /tmp/datos
      # Recursos requeridos por este contenedor. No se puede actualizar.
      resources:
        # Los límites describen la cantidad máxima de recursos informáticos permitidos.
        limits:
          memory: "128Mi"
          cpu: "500m"
  # List of volumes that can be mounted by containers belonging to the pod.
  volumes:
    # El volumen representa un volumen con nombre en un pod al que puede acceder cualquier contenedor del pod.
    - name: volumen-secretos
    # Representa un secreto que debería poblar este volumen.
      secret:
      # Nombre del secreto que se utilizará en el espacio de nombres del pod.
        secretName: secreto-volumen
  # Política de reinicio
  restartPolicy: Never
