apiVersion: v1
kind: Pod
metadata:
  name: ejemplo
# Especificación del comportamiento deseado del pod
spec:
  # Lista de contenedores pertenecientes al pod. Actualmente no se pueden agregar ni eliminar contenedores. 
  # Debe haber al menos un contenedor en un Pod. No se puede actualizar.
  containers:
    # Nombre del contenedor especificado como DNS_LABEL. Cada contenedor de un pod 
    # debe tener un nombre único (DNS_LABEL). No se puede actualizar.
    - name: ejemplo
      # Nombre de la imagen del contenedor.
      image: apasoft/web1
      # Recursos requeridos por este contenedor. No se puede actualizar.
      resources:
        # Los límites describen la cantidad máxima de recursos informáticos permitidos.
        limits:
          memory: "128Mi"
          cpu: "500m"
  #Es una lista opcional de referencias a secretos en el mismo espacio de nombres 
  #(namespace) que se utilizarán para recuperar cualquiera de las imágenes utilizadas
  #por esta especificación de Pod (PodSpec). Si se especifica, estos secretos se pasarán
  #a las implementaciones individuales del recuperador (puller) para que los utilicen.
  #([]LocalObjectReference)
  imagePullSecrets:
    - name: midocker

# Comando para crear el SECRET DOCKER
# kubectl create secret docker-registry nombre-del-secret --docker-server=REGISTRO_DOCKER --docker-username=USUARIO --docker-password=CONTRASEÑA --docker-email=CORREO_ELECTRONICO