apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  #NodeName es una solicitud para programar este pod en un nodo específico. 
  #Si no está vacío, el planificador simplemente programa este pod en ese nodo,
  #suponiendo que cumple con los requisitos de recursos.
  nodeName: worker-01
