apiVersion: v1
kind: Pod
metadata:
  name: postgres-db1
spec:
  containers:
    - image: postgres:11
      name: postgres-db1
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume1
      env:
        - name: POSTGRES_PASSWORD
          value: "secret"
        - name: POSTGRES_USER
          value: "odoo"
        - name: POSTGRES_DB
          value: "postgres"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: postgres-db-volume1
      persistentVolumeClaim:
        claimName: pvc-bbdd
