apiVersion: v1
# PersistentVolume (PV) es un recurso de almacenamiento proporcionado
# por un administrador. Es análogo a un nodo.
kind: PersistentVolume
# Metadatos que todos los recursos persistentes deben tener, que incluyen
# todos los objetos que los usuarios deben crear.
metadata:
  # El nombre debe ser único dentro de un espacio de nombres. Es necesario al crear recursos,
  # aunque algunos recursos pueden permitir que un cliente solicite la generación de un nombre
  # apropiado automáticamente. El nombre está destinado principalmente a la creación de 
  # idempotencia y definición de configuración. No se puede actualizar.
  name: pv-bbdd-vol1
# Define una especificación de un volumen persistente propiedad del clúster. Proporcionado por
# un administrador
spec:
  # Nombre de StorageClass a la que pertenece este volumen persistente. El valor vacío significa
  # que este volumen no pertenece a ninguna StorageClass.
  storageClassName: bbdd
  # La descripción de los recursos y la capacidad del volumen persistente.
  capacity:
    storage: 10Gi
  # Contiene todas las formas en que se puede montar el volumen.
  accessModes:
    - ReadWriteOnce
  # Representa un directorio en el host. Provisto por un desarrollador o evaluador. ¡Esto es útil
  # únicamente para desarrollo y pruebas de un solo nodo! El almacenamiento en el host no es
  # compatible de ninguna manera y NO FUNCIONARÁ en un clúster de múltiples nodos
  hostPath:
    path: "/tmp/bbdd-vol1"
